### ISSUE TITLE
bug: latest version not found when patch for older version exists 

### ISSUE THREAD

**Issue by larsl-net** [hymenaios-io/Hymenaios#10]
**Describe the bug**
Currently I get for [rancher](https://github.com/rancher/rancher) as the latest version the 2.5.13, although the latest version is the 2.6.4.

This is probably because the 2.5.13 was the last to be released.

**To Reproduce**
Use the following config
```yaml
service:
  rancher/rancher:
    type: github
    url: rancher/rancher
    url_commands:
      - type: regex_submatch
        regex: v([0-9.]+)$
    web_url: https://github.com/rancher/rancher/releases/v{{ version }}
    icon: https://raw.githubusercontent.com/rancher/docs/master/static/imgs/rancher-logo-cow-blue.svg
    status:
      current_version: 2.6.3
      current_version_timestamp: "2022-04-22T20:29:51Z"
      latest_version: 2.5.13
      latest_version_timestamp: "2022-04-22T20:29:51Z"
```
