### ISSUE TITLE
bug: Icons can overflow (too wide)

### ISSUE THREAD

**Issue by larsl-net** [hymenaios-io/Hymenaios#14]
**Describe the bug**
The icons on the web UI are too wide in some situations. See screenshot. 

**To Reproduce**
I use the following config
```yaml
service:
  netbox-community/netbox:
    type: github
    url: netbox-community/netbox
    url_commands:
      - type: regex_submatch
        regex: v([0-9.]+)$
    regex_version: ^[0-9.]+$
    web_url: https://github.com/netbox-community/netbox/releases/tag/v{{ version }}
    icon: https://github.com/netbox-community/netbox/raw/develop/netbox/project-static/img/netbox_logo.svg
    deployed_version:
      url: https://netbox.example.io/
      regex: '[0-9a-z]+ \(v([0-9.]+)\)'
  requarks/wiki:
    type: github
    url: requarks/wiki
    url_commands:
      - type: regex_submatch
        regex: v([0-9.]+)$
    regex_version: ^[0-9.]+$
    web_url: https://github.com/requarks/wiki/releases/tag/v{{ version }}
    icon: https://raw.githubusercontent.com/requarks/wiki/main/client/static/svg/logo-wikijs-full.svg
```

**Screenshots**
![Bug_Image_size](https://user-images.githubusercontent.com/33843261/164886588-23374690-86fa-4785-93cf-67d630dddef6.png)
