### ISSUE TITLE
Version not being returned for deployed service from json

### ISSUE THREAD

**Issue by samcro1967** [hymenaios-io/Hymenaios#31]
**Describe the bug**
Trying to get the current version of sonarr and it is not being returned from the json.

**To Reproduce**

**config.xml**
```
  Sonarr/Sonarr:
    type: url
    url: https://github.com/Sonarr/Sonarr/tags
    url_commands:
      - type: regex_submatch
        regex: \/releases\/tag\/v?([0-9.]+)\"
    web_url: http://osu.sonarr:8079/sonarr/system/updates
    icon: https://raw.githubusercontent.com/NX211/homer-icons/master/png/sonarr.png
    deployed_version:
      url: http://local.sonarr:8079/sonarr/api/v3/system/status?apikey=<redacted>
      json: version
```
**Sonarr json**
```
{
  "appName": "Sonarr",
  "version": "3.0.8.1519",
  "buildTime": "2022-05-09T22:34:37Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": false,
  "isUserInteractive": false,
  "startupPath": "/app/sonarr/bin",
  "appData": "/config",
  "osName": "Linux",
  "isMonoRuntime": true,
  "isMono": true,
  "isLinux": true,
  "isOsx": false,
  "isWindows": false,
  "mode": "console",
  "branch": "develop",
  "authentication": "none",
  "sqliteVersion": "3.36.0",
  "urlBase": "/sonarr",
  "runtimeVersion": "6.12.0.122",
  "runtimeName": "mono",
  "startTime": "2022-05-14T12:06:39.675145Z",
  "packageVersion": "3.0.8.1519-ls282",
  "packageAuthor": "[linuxserver.io](https://www.linuxserver.io/)",
  "packageUpdateMechanism": "docker"
}
```

**Expected behavior**
Current version is returned from the json

**Screenshots**
![image](https://user-images.githubusercontent.com/2319445/168430010-e1775336-cbd4-4e9b-bd83-5a1513cc698c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome 101.0.4951.54
 - Hymenaios Version: 0.3.2
 - Docker: 20.10.16

**Additional context**
I tried the regex below instead of json with no luck either.  Also tried headers with key and value instead of embedding them in the URL.
```
regex: \s\s\"version\":\s\"([0-9.]+)\",
```
