### ISSUE TITLE
feat(query): Support for retrieving the current version from the service itself

### ISSUE THREAD

**Issue by larsl-net** [hymenaios-io/Hymenaios#7]
**Is your feature request related to a problem? Please describe.**
Updating the current version is difficult in setups with many tools and automatic updating.

**Describe the solution you'd like**
The possibility to update the current version of a software automatically via a kind of web monitor. With the possibility to use Basic Auth or Custom Header.

Example an API call for Authentik on https://authentik.example.com/api/v3/admin/version/ to get the current version

**Comment by JosephKav** [comment]
Good idea!

So this is asking for something like `current_version.url` support on each Service? We monitor the URL/GitHub for the latest_version and would use this to find the current_version

**Comment by JosephKav** [comment]
Right, I've got this working on the branch linked to this issue. Tested it working with that Authentik URL. Have made it support both RegEx and JSON filtering of the version from that page, so it should support regular pages if they're like Gitea and display the current version. Authentik threw me off for a bit requiring the header to be 'bearer API_KEY' and not just 'API_KEY'. I haven't tested basic_auth, but it looks like a standard feature in the http library, so I've just allowed that as a param and added a `req.SetBasicAuth(Username, Password)`.

Authentik:
```
deployed_version:
  url: https://authentik.example.io/api/v3/admin/version/
  headers:
    - key: Authorization
      value: bearer API_KEY
  json: version_current
```

Gitea:
```
deployed_version:
  url: https://gitea.example.io
  regex: 'Powered by Gitea Version: ([0-9.]) '
```
I'll put together some info for the site and most likely release this on Friday (today).

**Comment by larsl-net** [comment]
The current implementation works.

However, I have discovered a point that can lead to problems.
With JSON returns it is not possible to use a path for the version.

Example return from Wiki.js:
```json
{"data":{"system":{"info":{"currentVersion":"2.5.278"}}}}
```
From me originally expected `json` specification was `data.system.info.currentVersion` which however does not work.

The actual working solution is to use only the last part in this case `currentVersion`.
```yaml
service:
  requarks/wiki:
    type: github
    url: requarks/wiki
    url_commands:
      - type: regex_submatch
        regex: v([0-9.]+)$
    regex_version: ^[0-9.]+$
    web_url: https://github.com/requarks/wiki/releases/tag/v{{ version }}
    icon: https://static.requarks.io/logo/wikijs-butterfly.svg
    deployed_version:
      url: https://wiki.example.io/graphql?query=%7Bsystem%7Binfo%7BcurrentVersion%7D%7D%7D
      headers:
        - key: Authorization
          value: Bearer <TOKEN>
      json: currentVersion
```

I think it would be good to support specifying a path in case the required key exists multiple times.
A theoretical example where the current version might cause problems
```json
{
  "Part1": {
    "version": "1.0.1"
  },
  "Part2":{
    "version": "3.0.1"
  }
}
```
